logging:
  level:
    root: INFO
    io.kafbat.ui: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonEncoder: DEBUG
    #org.springframework.http.codec.json.Jackson2JsonDecoder: DEBUG
    reactor.netty.http.server.AccessLog: INFO
    org.springframework.security: DEBUG

#server:
#  port: 8080 #- Port on which the app will run.

spring:
  jmx:
    enabled: true
  ldap:
    urls: ldap://localhost:10389
    base: "cn={0},ou=people,dc=planetexpress,dc=com"
    admin-user: "cn=admin,dc=planetexpress,dc=com"
    admin-password: "GoodNewsEveryone"
    user-filter-search-base: "dc=planetexpress,dc=com"
    user-filter-search-filter: "(&(uid={0})(objectClass=inetOrgPerson))"
    group-filter-search-base: "ou=people,dc=planetexpress,dc=com"

kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:9092
      schemaRegistry: http://localhost:8085
      ksqldbServer: http://localhost:8088
      kafkaConnect:
        - name: first
          address: http://localhost:8083
      metrics:
        port: 9997
        type: JMX

dynamic.config.enabled: true

oauth2:
  ldap:
    activeDirectory: false
    activeDirectory.domain: domain.com

auth:
  type: DISABLED
  #  type: OAUTH2
  #  type: LDAP
  oauth2:
    client:
      cognito:
        clientId: # CLIENT ID
        clientSecret: # CLIENT SECRET
        scope: openid
        client-name: cognito
        provider: cognito
        redirect-uri: http://localhost:8080/login/oauth2/code/cognito
        authorization-grant-type: authorization_code
        issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M7cIUn1nj
        jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M7cIUn1nj/.well-known/jwks.json
        user-name-attribute: cognito:username
        custom-params:
          type: cognito
          logoutUrl: https://kek.net/logout
      google:
        provider: google
        clientId: # CLIENT ID
        clientSecret: # CLIENT SECRET
        user-name-attribute: email
        custom-params:
          type: google
          allowedDomain: kafbat.dev
      github:
        provider: github
        clientId: # CLIENT ID
        clientSecret: # CLIENT SECRET
        scope:
          - read:org
        user-name-attribute: login
        custom-params:
          type: github

rbac:
  roles:
    - name: "memelords"
      clusters:
        - local
      subjects:
        - provider: oauth_google
          type: domain
          value: "kafbat.dev"
        - provider: oauth_google
          type: user
          value: "name@kafbat.dev"

        - provider: oauth_github
          type: organization
          value: "kafbat"
        - provider: oauth_github
          type: user
          value: "memelord"

        - provider: oauth_cognito
          type: user
          value: "username"
        - provider: oauth_cognito
          type: group
          value: "memelords"

        - provider: ldap
          type: group
          value: "admin_staff"

        # NOT IMPLEMENTED YET
      #        - provider: ldap_ad
      #          type: group
      #          value: "admin_staff"

      permissions:
        - resource: applicationconfig
          actions: all

        - resource: clusterconfig
          actions: all

        - resource: topic
          value: ".*"
          actions: all

        - resource: consumer
          value: ".*"
          actions: all

        - resource: schema
          value: ".*"
          actions: all

        - resource: connect
          value: ".*"
          actions: all

        - resource: ksql
          actions: all

        - resource: acl
          actions: all

        - resource: audit
          actions: all
aws:
  region: eu-west-1

sainsburys:
  external:
    services:
      service-now:
        base-url: ${SAINSBURYS_EXTERNAL_SERVICES_SERVICENOW_BASE_URL}
        authentication:
          api-key: ${SAINSBURYS_EXTERNAL_SERVICES_SERVICENOW_AUTH_KEY}
          api-secret: ${SAINSBURYS_EXTERNAL_SERVICES_SERVICENOW_AUTH_SECRET}
        operations:
          create: '/api/now/v1/import/u_generic_incident_inbound'
        requests:
          content:
            u_assigned_to: ${SAINSBURYS_EXTERNAL_SERVICES_SERVICENOW_EMAIL_ADDRESS}
            u_assignment_group: CORE Kafka Tech Support
            u_business_service: Not Configured
            u_caller_id: '' #Kafbat user principal is populated internally
            u_category: Software
            u_subcategory: Application
            u_cmdb_ci: Kafka - Kafbat UI
            u_comments: Kafbat Data Unmasking Incident
            u_description: 'Kafka Cluster: <kafka_cluster>
              Kafka Topic: <kafka_topic>
              Justification: <justification>'
            u_impact: 4 #Low Impact Status
            u_urgency: 4 #Low urgency Status
            u_impacted_parties: KafbatUI Services
            u_location_not_found: true
            u_undefined_location: Ticket raised for audit KafbatUI
            u_short_description: Kafbat Data Unmasking Request
            u_state: 6 #Resolved state in ServiceNow - No action required
            u_work_notes: Audit incident for kafbat data unmasking.

      confluent-api:
        base-url: 'http://localhost:8080'
        operations:
          retrieve:
            tagdefs: '/catalog/v1/types/tagdefs?deleted=false'
            topic: '/catalog/v1/search/basic?type=kafka_topic'
            topic.fields: '/api/v1/search/topics/fields'
            schema: '/api/v1/search/entities?type=sr_field'
            subject: '/subjects/{topic}-value/versions/latest'

  masking:
    feature:
      enabled: ${SAINSBURYS_DATA_MASKING_FEATURE_ENABLED}
    rule:
      cluster:
        unmasked-prefix: 'unmasked-'
      time-to-live: 3600000 #60 minutes in millis
      chars-replacement:
        - X
        - x
        - x
        - -
      topic-replacement: '[CONFIDENTIAL]'
      tags:
        schema-field: sainsburys.dataClassification #avro schema field masking custom tag
    scheduler:
      update-masking-tags-rate-millis: ${SAINSBURYS_MASKING_SCHEDULER_MILLIS} #60 minutes in millis
      update-rbac-rate-millis: ${SAINSBURYS_RBAC_SCHEDULER_MILLIS} #60 minutes in millis
    subject:
      type: user

    date:
      format: 'yyyy-MM-dd HH:mm:ss.SSS'
