---
version: '3'

services:

  # https://github.com/aerokube/selenoid/releases
  selenoid:
    network_mode: bridge
    image: aerokube/selenoid:1.11.2
    volumes:
      - "../selenoid/config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "../target/selenoid-results/video:/opt/selenoid/video"
      - "../target/selenoid-results/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=../docker/selenoid/video
    ports:
      - "4444:4444"
    command: [ "-limit", "5", "-conf", "/etc/selenoid/browsers-local.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]

  # https://github.com/aerokube/selenoid-ui/releases
  selenoid-ui:
    network_mode: bridge
    image: aerokube/selenoid-ui:1.10.11
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  # https://aerokube.com/images/latest
  selenoid-chrome:
    image: selenoid/vnc_chrome:117.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - selenoid
      - selenoid-ui
