package io.kafbat.ui.model;

public enum ClusterFeature {
  KAFKA_CONNECT,
  KSQL_DB,
  SCHEMA_REGISTRY,
  TOPIC_DELETION,
  KAFKA_ACL_VIEW,
  KAFKA_ACL_EDIT,
  CLIENT_QUOTA_MANAGEMENT,
  GRAPHS_ENABLED,
  FTS_ENABLED,
  FTS_DEFAULT_ENABLED,
  MESSAGE_RELATIVE_TIMESTAMP
}
