version: "0.2"

settings:


maintainers: &maintainers
  teams: [ "maintainers" ]
  users: [ ]

anchors:

  skip_main: &skip_off
    enabled: false

  skip_maintainers: &skip_maintainers
    enabled: true
    conditions:
      authors: *maintainers

  keyword-labeling: &keyword-labeling
    enabled: true
    case-sensitive: false
    scan:
      title: true
      body: false
    rules:
      # <alias>: [ <labels> ]
      acl: [ "area/acl" ]
      audit: [ "area/audit" ]
      auth: [ "area/auth" ]
      consumers: [ "area/consumers" ]
      messages: [ "area/messages" ]
      rbac: [ "area/rbac" ]
      serde: [ "area/serde" ]
      SR: [ "area/sr" ]
      topics: [ "area/topics" ]
      ux: [ "area/ux" ]
      wizard: [ "area/wizard" ]
      ###
      backend: [ "scope/backend" ]
      frontend: [ "scope/frontend" ]
      infra: [ "scope/infra" ]
      ###
      bug: [ "type/bug" ]
      feature: [ "type/feature" ]
      enh: [ "type/enhancement" ]

  automatic: &automatic
    enabled: true
    skip: *skip_off
    label: "status/triage"
    remove-assignees: false
    keyword-labeling: *keyword-labeling
    completed:
      labels:
        add: [ "status/triage/completed" ]
        remove: []

  manual: &manual
    enabled: true
    skip: *skip_maintainers
    label: "status/triage/manual"
    labels:
      add: [ ]
      remove: [ ]
    assign-maintainers: false

  repeating: &repeating
    enabled: false
    skip: *skip_maintainers
    triggers:
      reopen: false
      triage-labels: false
      labels: [ "status/retriage" ]

  feedback-management: &feedback-management
    enabled: true
    labels:
      requested: "status/feedback-requested"
      received: "status/feedback-received"
    only-author-replies: false
    assign-author: true
    assign-maintainers: false
    auto-close:
      enabled: true
      close-days: 7
      labels:
        add: [ "status/stale" ]
        remove: [ "status/feedback-requested" ]

  locking: &locking
    enabled: false

  triage: &triage
    enabled: true

    automatic: *automatic
    manual: *manual
    repeating: *repeating

issues:
  triage: *triage
  feedback-management: *feedback-management
  locking: *locking

prs:
  triage: *triage
  feedback-management: *feedback-management
  locking: *locking

  auto-rebase:
    enabled: false

comments:
  feedback:
    requested: "Further user feedback is requested. Please reply within 7 days or we might close the issue."
    received: "Thanks for the additional feedback! We'll get back to your issue soon."
    closed: "No feedback received within 7 days. Auto closing."
