name: "Backend: tests & sonar"

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Original github.event_name'
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # https://github.com/actions/checkout/releases/tag/v4.0.0
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # https://github.com/actions/setup-java/releases/tag/v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: "Tests"
        run: |
          ./gradlew :api:test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # https://github.com/codecov/codecov-action/releases/tag/v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: api/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          fail_ci_if_error: false
