name: "Backend: tests & sonar"

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Original github.event_name'
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # https://github.com/actions/setup-java/releases/tag/v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: "Tests"
        run: |
          ./gradlew :api:test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # https://github.com/codecov/codecov-action/releases/tag/v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: api/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          fail_ci_if_error: false
