name: "Backend: tests & sonar"

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Original github.event_name'
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # https://github.com/actions/checkout/releases/tag/v4.2.2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # https://github.com/actions/setup-java/releases/tag/v4.6.0
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: "Tests"
        run: |
          ./gradlew :api:test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # https://github.com/codecov/codecov-action/releases/tag/v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: api/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          fail_ci_if_error: false
