name: "Backend: PR: Build and test"

on:

  pull_request:
    types: [ "opened", "reopened", "synchronize" ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # https://github.com/dorny/paths-filter/releases/tag/v4.0.1
        id: filter
        with:
          filters: |
            backend:
              - "build.gradle"
              - "gradle.properties"
              - "settings.gradle"
              - "gradle/libs.versions.toml"
              - "contract/**"
              - "api/**"
              - "serde-api/**"

  build-and-test:
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend_tests.yml
    with:
      event_name: ${{ github.event_name }}
