name: "Infra: Feature Testing: Destroy env"

on:
  workflow_dispatch:
  pull_request:
    types: ['unlabeled', 'closed']

permissions:
  contents: read

jobs:
  remove:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'status/feature_testing' || (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'status/feature_testing')) }}
    steps:
      - name: clone infra
        run: |
          git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/kafbat/infra.git --branch envs
      - name: remove env
        run: |
          cd infra/scripts
          bash pr-env-remove.sh pr${{ github.event.pull_request.number }}
          git config --global user.email "infra@kafbat.io"
          git config --global user.name "infra-tech"
          cd ../..
          git -C infra add -A
          git -C infra commit -m "remove env: pr${{ github.event.pull_request.number }}" && git -C infra push || true
