name: "E2E: Suite run"
on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select test suite to run'
        default: 'regression'
        required: true
        type: choice
        options:
          - regression
          - sanity
          - smoke

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    uses: ./.github/workflows/e2e-run.yml
    secrets: inherit
    with:
      suite_name: ${{ github.event.inputs.test_suite }}
      sha: ${{ github.sha }}
