name: "E2E: Weekly suite"
on:
  schedule:
    - cron: '0 1 * * 1'

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    uses: ./.github/workflows/e2e-run.yml
    secrets: inherit
    with:
      suite_name: "sanity"
      sha: ${{ github.sha }}
