name: "E2E: Playwright Manual run"
on:
  workflow_dispatch:
    sha:
      required: true
      type: string

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  build-and-test:
    uses: ./.github/workflows/e2e-playwright-run.yml
    secrets: inherit
    with:
      sha: ${{ inputs.sha }}


