name: "Frontend: PR: Build and test"

on:

  pull_request_target:
    types: [ "opened", "reopened", "synchronize" ]
    paths:
      - "contract/**"
      - "frontend/**"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: ./.github/workflows/frontend_tests.yml
