name: "Infra: Feature Testing Public: Destroy env"
on:
  workflow_dispatch:
    inputs:
      ENV_NAME:
        description: 'Will be used to remove previously deployed separate environment.'
        required: true
        default: 'demo'

jobs:
  separate-env-remove:
    runs-on: ubuntu-latest
    steps:
      - name: clone infra
        run: |
          git clone https://infra-tech:${{ secrets.INFRA_USER_ACCESS_TOKEN }}@github.com/kafbat/infra.git --branch envs
      - name: remove separate environment
        run: |
          cd infra/scripts
          bash pr-env-remove.sh ${{ github.event.inputs.ENV_NAME }}
          git config --global user.email "infra@kafbat.io"
          git config --global user.name "infra-tech"
          cd ../..
          git -C infra add -A
          git -C infra commit -m "separate env removed: ${{ github.event.inputs.ENV_NAME }}" && git -C infra push || true
