name: "test"
on:
  push:
    branches:
      - infra/fix-permissions-for-checkout
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v4
    - name: pwd
      run: pwd
    - name: list files
      run: ls -lah