# Docs: https://github.com/gradle/actions/blob/main/docs/wrapper-validation.md
name: "Validate Gradle Wrapper"

on:
  push:
    paths:
      - gradle/wrapper/gradle-wrapper.jar
  pull_request:
    paths:
      - gradle/wrapper/gradle-wrapper.jar

jobs:
  validation:
    name: "Validate Gradle Wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1
      - uses: gradle/actions/wrapper-validation@9c971963bec38e04b3d30dcc455b5382be2fdbfb # https://github.com/gradle/actions/releases/tag/v6.3.0
