name: "Infra: Workflow linter"
on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  lint-workflows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # https://github.com/actions/checkout/releases/tag/v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - name: Install yamllint
        run: sudo apt install -y yamllint

      - name: Validate workflow yaml files
        run: yamllint .github/workflows/. -d relaxed -f github --no-warnings
